# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'osp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tosp.proto\x12\x03osp\"S\n\rTileFootprint\x12\x0f\n\x07lat_min\x18\x01 \x01(\x01\x12\x0f\n\x07lat_max\x18\x02 \x01(\x01\x12\x0f\n\x07lon_min\x18\x03 \x01(\x01\x12\x0f\n\x07lon_max\x18\x04 \x01(\x01\"h\n\x07\x41nomaly\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.osp.AnomalyType\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x0f\n\x07\x62\x62ox_px\x18\x05 \x03(\x05\"\xdf\x01\n\nSceneBrief\x12\x10\n\x08scene_id\x18\x01 \x01(\t\x12\x15\n\rtimestamp_utc\x18\x02 \x01(\t\x12*\n\x0etile_footprint\x18\x03 \x01(\x0b\x32\x12.osp.TileFootprint\x12\x13\n\x0b\x63loud_cover\x18\x04 \x01(\x02\x12\x1f\n\tanomalies\x18\x05 \x03(\x0b\x32\x0c.osp.Anomaly\x12\x14\n\x0cinference_ms\x18\x06 \x01(\x02\x12\x15\n\rmodel_version\x18\x07 \x01(\t\x12\x19\n\x11\x63ompression_ratio\x18\x08 \x01(\x03*P\n\x0b\x41nomalyType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04SHIP\x10\x01\x12\x0c\n\x08\x41IRPLANE\x10\x02\x12\x10\n\x0cSTORAGE_TANK\x10\x03\x12\n\n\x06HARBOR\x10\x04\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_ANOMALYTYPE']._serialized_start=435
  _globals['_ANOMALYTYPE']._serialized_end=515
  _globals['_TILEFOOTPRINT']._serialized_start=18
  _globals['_TILEFOOTPRINT']._serialized_end=101
  _globals['_ANOMALY']._serialized_start=103
  _globals['_ANOMALY']._serialized_end=207
  _globals['_SCENEBRIEF']._serialized_start=210
  _globals['_SCENEBRIEF']._serialized_end=433
# @@protoc_insertion_point(module_scope)
